extends Resource
class_name LevelThumbnails

## Centralized registry of preloaded level thumbnails
## This ensures thumbnails are always available in web builds
## Auto-generated by level_thumb_baker plugin

# Preloaded thumbnails (PNG files work fine with compression disabled)
const THUMBNAILS := {
	"level01": preload("res://assets/level_thumbs/level01.png"),
	"level02": preload("res://assets/level_thumbs/level02.png"),
}

## Get thumbnail for a level path
static func get_thumbnail(level_path: String) -> Texture2D:
	var basename := level_path.get_file().get_basename()
	if THUMBNAILS.has(basename):
		return THUMBNAILS[basename]
	return null

## Get all available level names that have thumbnails
static func get_available_levels() -> Array[String]:
	var levels: Array[String] = []
	levels.assign(THUMBNAILS.keys())
	return levels
